# Generated by Django 5.1.5 on 2025-02-22 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecursionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        max_length=20,
                    ),
                ),
                ("interval", models.IntegerField(default=1)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "tasks_recursion_rule",
            },
        ),
    ]
