# Generated by Django 5.1.5 on 2025-02-21 13:31

from django.db import migrations


# finish this tomorrow
def create_initial_rules(apps, schema_editor):
    # We need to get the historical version of the model
    RecursionRule = apps.get_model("tasks", "RecursionRule")

    # Since we can't directly import the model class with TextChoices,
    # we need to use the string values directly

    # Daily rule
    RecursionRule.objects.create(frequency="daily", interval=1)

    # Weekly rule (weekdays)
    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[0],
    )

    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[1],
    )
    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[2],
    )

    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[3],
    )
    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[4],
    )
    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[5],
    )

    RecursionRule.objects.create(
        frequency="weekly",
        interval=1,
        days_of_week=[6],
    )


def remove_initial_rules(apps, schema_editor):
    RecursionRule = apps.get_model("tasks", "RecursionRule")
    RecursionRule.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "tasks",
            "0001_create_recursion_rules_table",
        ),
    ]

    operations = [
        migrations.RunPython(create_initial_rules, remove_initial_rules),
    ]
