# Generated by Django 5.1.5 on 2025-02-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_create_task_template_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In progress'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.tasktemplate')),
            ],
            options={
                'db_table': 'tasks_task_instance',
                'indexes': [models.Index(fields=['template', 'created_at'], name='tasks_task__templat_8eec3a_idx'), models.Index(fields=['task_status', 'created_at'], name='tasks_task__task_st_0f39c2_idx'), models.Index(fields=['due_date'], name='tasks_task__due_dat_e25db1_idx')],
            },
        ),
    ]
