# Generated by Django 5.1.5 on 2025-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_create_task_instance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='name',
            field=models.CharField(default='task', max_length=255),
        ),
    ]
