# Generated by Django 5.1.5 on 2025-02-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasktemplate_description_tasktemplate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='request_body',
        ),
    ]
