# Generated by Django 5.1.2 on 2025-03-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskinstance_tasks_task__task_st_0f39c2_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinstance',
            old_name='finished_time',
            new_name='finished_at',
        ),
    ]
